### ISSUE TITLE
行间公式编辑时 copilot 会自动替换

### ISSUE THREAD

**Issue by GaisaiYuno** [Snowfly-T/typora-copilot#1]
行间公式编辑时 copilot 会自动替换，无法选择

**Comment by GaisaiYuno** [comment]
而且在禁用copilot时行间公式仍然会吞行数

**Comment by Snowfly-T** [comment]
行间公式之前没注意过，我看下之后的版本能不能修复。

目前对于 Normal 模式 CodeMirror 中（Code Block 或行间公式、HTML 代码块等）的补全使用的是 Source Mode 中的 Completion text 的显示方式。但看起来在 Normal 模式下这东西 BUG 很多，很容易污染内容和历史记录😂我尝试在之后的版本中加个选项允许切换为那种 Suggesion panel 的常规方式来接受补全。

**Comment by Snowfly-T** [comment]
https://github.com/Snowfly-T/typora-copilot/commit/2f0e4500f688e41eb73b7722dd36ae0d4caed187
