### ISSUE TITLE
MacOS bugfix

### ISSUE THREAD

**Issue by evaldsurtans** [Snowfly-T/typora-copilot#2]
for macos change 

`yield runShellCommand(command);`

to

`runShellCommand(command);`

then it works

**Comment by evaldsurtans** [comment]
Great plugin and clean code, thank you, happy if you add me to Git as contributor or will make fork and pull requests

**Comment by Snowfly-T** [comment]
I‘d welcome a PR on that. The await in the code seems superfluous and could be omitted. I haven't experienced any related issues on my MacBook Pro M2, so it might be a compatibility problem unique to certain devices.

Also, our repository's commitlint might be somewhat strict, adhering to the standards of the VSCode git-commit-plugin, which could aid you in making your PR submission more seamless :)

**Comment by Snowfly-T** [comment]
Fixed in 267c1e18e56008f5c30834abb9eaa7daba0603fa.
